# -*- coding: utf-8 -*-
"""Business_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hwy2Fs3HDUkXoiTX9NHOPvBMw36dfa4o
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')



! pip install pandas

df = pd.read_excel('/content/IBM_Attrition T.xlsx')

df

df['Attrition'].value_counts()

attrited= df['Attrition'].value_counts()
attrited

! pip install numpy
! pip install matplotlib

plt.pie(attrited,labels= attrited.index, autopct= '%0.2f%%')
plt.show()

df.groupby('Attrition')['Age'].mean()
#interpretation: the employees who is attriting are belonging to lower age group

plt.boxplot(df['Age'])
plt.show()

People_leaving= df[df['Attrition']=='Yes']
People_leaving

People_leaving['BusinessTravel'].value_counts()
#the people who does'nt travel at all are less in count compared to people who travel
#rarely

People_leaving.groupby('BusinessTravel')['DailyRate'].mean()

#out of the people who are attriting we see that non travellers has a high daily rate compared to people who make any travel

People_leaving['Department'].value_counts()

